### ISSUE TITLE
Feature - Add individual container class

### ISSUE THREAD

**Issue by Ma3xl3** [markocupic/contao-article-class-select-bundle#1]
First, thanks for your great plugin!
Is it possible to add an additional text input field (in the backend) to include some individual container classes by the user?

```
<div class="article-inside container MYCLASS1 MYCLASS2">
    ....
</div>
```

**Comment by markocupic** [comment]
Why you do not use the default css-class textfield of the contao core?

**Comment by Ma3xl3** [comment]
If you select the container-fluid class you have a padding left and right.
To reset this padding you have to add "px-0" class in bootstrap.

```
<div class="article-inside container-fluid px-0">
    ....
</div>

**Comment by markocupic** [comment]
Du könntest auch die dca anpassen und eine zusätzliche select Option einfügen
"container p-0"
Oder nicht?

**Comment by Ma3xl3** [comment]
Korrekt ... so wäre es natürlich auch möglich 👍

**Comment by markocupic** [comment]
@Ma3xl3 
Schau mal ins aktuellste build:
  1fab9c184e7d27c62b7efe454c8d3958c79c3b3f

**Comment by Ma3xl3** [comment]
Perfekt 👍 Danke hierfür!
